version: "3.8"

services:
  node-server:
    build: .
    container_name: node-server-container
    ports:
      - "5000:5000"
    restart: always
    network_mode: "host"
    environment:
      - POCKETBASE_URL=http://172.17.0.1:8090

networks:
  app_network:
    external: true
